server_label = "SWRC Local Test Server"

# Internal update speed
update_speed = 250

# Attempted fix to multi-rc ithrun s1 situation
checkpoint_reset_speed = 5000

# Primary websocket's port
port = 7777

# Maximum session for RC
max_sessions_per = 1

[keychain.org.INTERNAL]
name = "Internal"
keys."Administrator" = { mc = "?", contact = "?" }

[keychain.org.FA]
name = "Formula Abex"
keys."Saisho" = { mc = "SaishoVibes", contact = "saishovibes" }
keys."Terraformer" = { mc = "terraformer9", contact = "terraformer" }
keys."Crazylegs" = { mc = "localhackerman", contact = "microwavedram", inc = 1 }

[keychain.org.IBRL]
name = "International boat racing league"
keys."Saisho" = { mc = "SaishoVibes", contact = "saishovibes" }
keys."Kaz" = { mc = "kazimierz3wielki", contact = "kazimierz_3_wielki" }
keys."Miesneus" = { mc = "Miesneus", contact = "miesneus" }

[keychain.org.EMC]
name = "EarthMC F1"
keys."Pie" = { mc = "PieTheHead", contact = "piethehead" }

[keychain.org.TF2]
name = "Towny F2"
keys."Pie" = { mc = "PieTheHead", contact = "piethehead" }

[keychain.org.LEAGUE_P]
name = "League P"
keys."R6" = { mc = "?", contact = "realr6itcannotbe02" }

[keychain.org.TURKEY]
name = "Turkey League"
keys."Subay" = { mc = "SubayAdamm", contact = "subayadamm" }

[keychain.org.EPF1]
name = "EarthPol F1"
keys."MattIsOff" = { mc = "MattIsOff", contact = "mattison" }
keys."Pwnings" = { mc = "pwnings", contact = "pwns." }
keys."AkselV" = { mc = "AkselV", contact = "aksel_v" }

[keychain.org.EMCF3]
name = "EarthMC F3"
keys."MemeReee" = { mc = "memexcx", contact = "memereee" }

[keychain.org.PROPA]
name = "Propa"
keys."Seggy" = { mc = "s3ggy", contact = "s3ggy_" }

[keychain.org.F1DMC]
name = "Diplomatica F1"
keys."Szick" = { mc = "?", contact = "prettyszick" }

[keychain.org.ARC]
name = "Abexlias Racing Championship"
keys."Swift" = { mc = "Swift_Master", contact = "swiftmaster1" }
keys."Nikolai" = { mc = "Urgentpancake", contact = "arctixgamer" }

[keychain.org.CR]
name = "Crusalis Chariot Racing"
keys."Deku" = { mc = "?", contact = "dekufullcowling" }

[motd]
swrc = "Welcome to 4.0.0"
rc = "Remember to set race state!"
racer = "FA will be remembered"

# Webserver configuration
[express]
enabled = true
port = 2145
